# Generated by Django 6.0.4 on 2026-04-26 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите архивный снимок', upload_to='retro_photos/%Y/%m/', verbose_name='Изображение')),
                ('year', models.IntegerField(help_text='Пример: 1950', verbose_name='Год съёмки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='locations.location', verbose_name='Локация')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Загрузивший пользователь')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='moderation.moderationstatus', verbose_name='Статус модерации')),
            ],
            options={
                'verbose_name': 'Архивное фото',
                'verbose_name_plural': 'Архивные фотографии',
                'ordering': ['-year', '-created_at'],
                'indexes': [models.Index(fields=['year'], name='photos_retr_year_baefa3_idx'), models.Index(fields=['status', 'created_at'], name='photos_retr_status__1188ca_idx')],
            },
        ),
    ]
