# Generated by Django 6.0.4 on 2026-04-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrophoto',
            name='azimuth',
            field=models.FloatField(blank=True, help_text='Направление камеры в градусах (0–360)', null=True, verbose_name='Азимут съёмки (градусы)'),
        ),
    ]
