# Generated by Django 6.0.4 on 2026-05-20 19:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_is_approved'),
        ('moderation', '0005_alter_moderationlog_options_and_more'),
        ('photos', '0002_retrophoto_azimuth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retrophoto',
            options={'ordering': ['-year', '-created_at'], 'verbose_name': 'Archive photo', 'verbose_name_plural': 'Archive photos'},
        ),
        migrations.AddField(
            model_name='retrophoto',
            name='shooting_azimuth',
            field=models.FloatField(blank=True, help_text='Направление камеры от точки съёмки в градусах (0-360)', null=True, verbose_name='Азимут съёмки'),
        ),
        migrations.AddField(
            model_name='retrophoto',
            name='shooting_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Географическая точка, откуда сделана фотография', null=True, srid=4326, verbose_name='Точка съёмки (где стоял фотограф)'),
        ),
        migrations.AlterField(
            model_name='retrophoto',
            name='azimuth',
            field=models.FloatField(blank=True, help_text='Camera direction in degrees from 0 to 360.', null=True, verbose_name='Shooting azimuth'),
        ),
        migrations.AlterField(
            model_name='retrophoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='retrophoto',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='retrophoto',
            name='image',
            field=models.ImageField(help_text='Upload an archive photo.', upload_to='retro_photos/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='retrophoto',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='retrophoto',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='retrophoto',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='moderation.moderationstatus', verbose_name='Moderation status'),
        ),
        migrations.AlterField(
            model_name='retrophoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='retrophoto',
            name='year',
            field=models.IntegerField(help_text='Example: 1950', verbose_name='Shooting year'),
        ),
    ]
