# Generated by Django 6.0.4 on 2026-04-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='photos.retrophoto', verbose_name='Фотография'),
        ),
    ]
