# Generated by Django 6.0.4 on 2026-05-20 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_moderationlog_action_seed_statuses'),
        ('photos', '0002_retrophoto_azimuth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-review_date'], 'verbose_name': 'Moderation log entry', 'verbose_name_plural': 'Moderation log'},
        ),
        migrations.AlterModelOptions(
            name='moderationstatus',
            options={'ordering': ['id'], 'verbose_name': 'Moderation status', 'verbose_name_plural': 'Moderation statuses'},
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Moderator comment'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Moderator'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='photos.retrophoto', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Review date'),
        ),
        migrations.AlterField(
            model_name='moderationstatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Status name'),
        ),
    ]
