# Generated by Django 6.0.4 on 2026-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название объекта'),
        ),
    ]
