# Generated by Django 6.0.4 on 2026-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_locationtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрена'),
        ),
    ]
